version: '3.7'
networks:
  audit-net:
    driver: bridge
services:
  test:
    image: ghcr.io/datakaveri/auditing-server-test:latest
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - /home/ubuntu/configs/5.6.0/audit-config-test.json:/usr/share/app/secrets/all-verticles-configs/config-dev.json
      - /home/ubuntu/configs/5.6.0/keystore-auditing.jks:/usr/share/app/secrets/keystore-auditing.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ./src/:/usr/share/app/src
      - ${WORKSPACE}:/tmp/test
      - ./iudx-pmd-ruleset.xml:/usr/share/app/iudx-pmd-ruleset.xml
      - ./google_checks.xml:/usr/share/app/google_checks.xml
    command: bash -c "docker/runTests.sh"
    network_mode: host
