openapi: 3.0.3
info:
  title: Activity API
  description: API for managing activity logs.
  version: 1.0.0
servers:
  - url: /api/v1

    # Global security definition (applies to all paths unless overridden)
security:
  - authorization: [ ]

paths:
  /dx/auditing/consumer/activity:
    get:
      operationId: get-ActivityLogs-for-consumer-user
      summary: Get all activity logs
      description: Retrieve a list of all activity logs.
      responses:
        '200':
          description: A list of activity logs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ActivityLog'
        '401':
          description: Unauthorized. Token is required.
        '500':
          description: Internal server error.

  /dx/auditing/admin/activity:
    get:
      operationId: get-activityLogs-for-admin-user
      summary: Get all activity logs
      description: Retrieve a list of all activity logs.
      responses:
        '200':
          description: A list of activity logs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ActivityLog'
        '401':
          description: Unauthorized. Token is required.
        '500':
          description: Internal server error.

  /dx/auditing/reportactivity/admin:
    get:
      operationId: get-admin-report
      summary: Admin Report
      description: Csv file for a list of activity logs for admin.
      parameters:
        - name: Authorization
          in: header
          description: A <b> valid data exchange Auth token(starting with Bearer) </b> to process the request. <br/> This field is <b> mandatory </b> for accessing a <b> report </b> .  <br/> If not provided with a valid token, user will be responded with <b> 401 Unauthorized </b> .
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Csv file generation Success. (send file data)
        '400':
          description: Bad request. No data available for CSV generation/Too many records.
        '401':
          description: Unauthorized. Token is required.
        '500':
          description: Internal server error.

  /dx/auditing/reportactivity/consumer:
    get:
      operationId: get-consumer-report
      summary: Consumer Report
      description: Csv file for a list of activity logs for consumer.
      parameters:
        - name: userid
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Unique identifier for the user.
        - name: Authorization
          in: header
          description: A <b> valid data exchange Auth token(starting with Bearer) </b> to process the request. <br/> This field is <b> mandatory </b> for accessing a <b> report </b> .  <br/> If not provided with a valid token, user will be responded with <b> 401 Unauthorized </b> .
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Csv file generation Success. (send file data)
        '400':
          description: Bad request. No data available for CSV generation/Too many records.
        '401':
          description: Unauthorized. Token is required.
        '500':
          description: Internal server error.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ActivityLog:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the activity log.
        name:
          type: string
          description: Name of the activity.
        description:
          type: string
          description: Description of the activity.
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the activity was created.
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the activity was last updated.
      required:
        - name
        - createdAt


    CsvFile:
      type: object
      properties:
        userid:
          type: string
          format: uuid
          description: Unique identifier for the activity log.
      required:
        - userid